apiVersion: v1
kind: PersistentVolume
metadata:
    name: finanztool-mediafiles-pvc
    namespace: finanztool
    labels:
        app: finanztool
        type: local
spec:
    selector:
        matchLabels:
            app: finanztool
    storageClassName: finanztool-mediafiles
    capacity:
        storage: 50Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/mnt/data'
