apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finanztool-mediafiles-pvc
  namespace: finanztool
  labels:
    app: finanztool
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
