apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: finanztool-ingress
    labels:
        app: finanztool
    namespace: finanztool
spec:
    entryPoints:
        - websecure
        - web
    routes:
        - match: Host(`finanz.frank.elsinga.de`) && PathPrefix(`/media/`)
          priority: 11
          services:
              - name: finanztool-svc
                port: 7000
          middlewares:
              - name: https
        - kind: Rule
          match: Host(`finanz.frank.elsinga.de`)
          priority: 10
          services:
              - name: finanztool-svc
                port: 8000
          middlewares:
              - name: https
    tls:
        secretName: finanz.frank.elsinga.de
