apiVersion: v1
kind: PersistentVolume
metadata:
    name: finanztool-pv
    namespace: finanztool
    labels:
        app: finanztool
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 100Mi
    Retain: Delete
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/mnt/data/finanztool'
