apiVersion: v1
kind: Service
metadata:
    name: finanztool-svc
    labels:
        app: finanztool
spec:
    type: NodePort
    selector:
        app: finanztool
    ports:
        - port: 8000
          targetPort: 8000
