image: python:3.7-buster

stages:
    - test
    - lint

before_script:
    - apt-get update
    - apt-get -qq install -y gettext texlive-base texlive-lang-german texlive-fonts-recommended texlive-latex-extra latexmk
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt -r requirements_dev.txt

pre-commit:
    stage: lint
    variables:
        PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
        PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - .cache/pip
            - .cache/pre-commit
            - venv
    script:
        - pip install pre-commit
        - pre-commit run --show-diff-on-failure --color=always --all-files
    needs: []

django-test:
    stage: test
    variables:
        PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - .cache/pip
            - venv
    script:
        - coverage run ./manage.py test --no-input
        - coverage xml
        - coverage report
    artifacts:
        reports:
            cobertura: coverage.xml
    needs: []
