# Generated by Django 3.2.3 on 2021-05-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='You may use placeholders for the subject.', max_length=200, verbose_name='Email subject')),
                ('text', models.TextField(help_text='You may use placeholders for the text.', verbose_name='Text')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueberfaellige_rechnung_mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ueberfaellige_rechnung_mail+', to='common.mail', verbose_name='Mailbenachrichtigung bei überfälligen Rechnungen')),
                ('zugewiesene_aufgabe_mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zugewiesene_aufgabe_mail+', to='common.mail', verbose_name='Mailbenachrichtigung über zugewiesene Aufgaben')),
            ],
        ),
    ]
