# Generated by Django 3.2.4 on 2021-06-03 22:08

from django.db import migrations, models


def clreate_initial_vip_qr_code(apps, _):
    QRCode = apps.get_model("common", "QRCode")
    rr_content = ("https://www.yo" "utub" "e.com/" "wat" "ch?v=dQw4w" "9WgXcQ",)
    QRCode.objects.create(pk=0, content=rr_content)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_settings_set_inactive_key_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=200, unique=True)),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes")),
            ],
        ),
        migrations.RunPython(clreate_initial_vip_qr_code),
    ]
