# Generated by Django 3.2.4 on 2021-06-04 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schluessel", "0014_alter_keylogentry_key_active"),
        ("common", "0004_qrcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="set_inactive_key_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="set_inactive_key_type+",
                to="schluessel.keytype",
                verbose_name="Keycard-Typ-Änderung, die falls dieser Keycard-Typ-Änderungens-antrag angenommen wird, "
                "den Schlüssel als inaktiv setzt. Bisherige Keycards werden nicht behandelt/ geupdated.",
            ),
        ),
    ]
