# Generated by Django 4.0.1 on 2022-01-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_settings_set_inactive_key_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="officediscount_shoppingcart",
            field=models.TextField(
                default="Protokollschokolade",
                verbose_name="Merkliste einer (Officediscount) Bestellung",
            ),
        ),
    ]
