# Generated by Django 3.2.4 on 2021-06-15 14:50

from django.db import migrations


def create_validation_service(apps, _):
    ValidationService = apps.get_model("otp_yubikey", "ValidationService")
    ValidationService.objects.get_or_create(
        name="default",
        defaults={"use_ssl": True, "param_sl": "", "param_timeout": ""},
    )


class Migration(migrations.Migration):
    dependencies = [
        ("otp_yubikey", "0002_auto_20200723_1650"),
        ("common", "0005_alter_settings_set_inactive_key_type"),
    ]

    operations = [
        migrations.RunPython(create_validation_service),
    ]
