# Generated by Django 4.0.3 on 2022-04-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_settings_officediscount_shoppingcart"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="at_05_remittance_information",
            field=models.CharField(
                default="",
                help_text="Used for generating an EPC-QR-Code",
                max_length=35,
                verbose_name="AT-05 Remittance Information (Structured) Creditor Reference "
                "(ISO 11649 RF Creditor Reference may be used)",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="at_20_iban",
            field=models.CharField(
                default="DE68702501500027003722",
                help_text="Used for generating an EPC-QR-Code",
                max_length=34,
                verbose_name="AT-20 Account number of the Beneficiary. Only IBAN is allowed.",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="at_21_name",
            field=models.CharField(
                default="Studienförderung der Fachschaft Mathematik/Physik/Informatik e. V.",
                help_text="Used for generating an EPC-QR-Code",
                max_length=70,
                verbose_name="AT-21 Name of the Beneficiary",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="at_23_bic",
            field=models.CharField(
                default="BYLADEM1KMS",
                help_text="Used for generating an EPC-QR-Code",
                max_length=11,
                verbose_name="AT-23 BIC of the Beneficiary Bank",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="at_44_purpose",
            field=models.CharField(
                default="",
                help_text="Used for generating an EPC-QR-Code",
                max_length=4,
                verbose_name="AT-44 Purpose of the Credit Transfer",
            ),
        ),
    ]
