# Generated by Django 3.2.3 on 2021-06-02 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("konto", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="einzahlungslog",
            old_name="timestamp",
            new_name="konto_last_einzahlung",
        ),
        migrations.AddField(
            model_name="einzahlungslog",
            name="einzahlungs_betreff",
            field=models.CharField(blank=True, max_length=378, null=True),
        ),
        migrations.AddField(
            model_name="einzahlungslog",
            name="konto_einlesen",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
