# Generated by Django 3.2.3 on 2021-06-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("konto", "0002_auto_20210602_2115"),
    ]

    operations = [
        migrations.RenameField(
            model_name="einzahlungslog",
            old_name="einzahlungs_betreff",
            new_name="latest_einzahlung_verwendungszweck",
        ),
        migrations.AddField(
            model_name="einzahlungslog",
            name="latest_einzahlung_betrag",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="einzahlungslog",
            name="konto_last_einzahlung",
            field=models.DateField(blank=True, null=True),
        ),
    ]
