# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 10:24
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Nummer')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Kommentar')),
            ],
        ),
        migrations.CreateModel(
            name='KeyLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[(('G',), 'Ausgabe'), (('R',), 'Rückgabe')], max_length=1,
                                               verbose_name='Aus-/Rückgabe')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schluessel.Key',
                                          verbose_name='Schlüssel')),
            ],
        ),
        migrations.CreateModel(
            name='KeyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=20, unique=True, verbose_name='Kurzname')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('deposit', models.FloatField(verbose_name='Kaution')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nachname')),
                ('firstname', models.CharField(max_length=200, verbose_name='Vorname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('address', models.CharField(max_length=200, verbose_name='Straße + Hausnummer')),
                ('plz', models.CharField(max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(max_length=200, verbose_name='Ort')),
                ('mobile', models.CharField(max_length=200, verbose_name='Mobil')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Telefon')),
            ],
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schluessel.Person',
                                    verbose_name='Entleiher'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Finanzer'),
        ),
        migrations.AddField(
            model_name='key',
            name='keytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schluessel.KeyType',
                                    verbose_name='Schlüssel-Typ'),
        ),
        migrations.AddField(
            model_name='key',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='schluessel.Person', verbose_name='Entleiher'),
        ),
    ]
