# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schluessel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keylogentry",
            name="operation",
            field=models.CharField(
                choices=[("G", "Ausgabe"), ("R", "Rückgabe")],
                max_length=1,
                verbose_name="Aus-/Rückgabe",
            ),
        ),
    ]
