# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schluessel", "0004_keytype_keycard"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="key",
            unique_together=set([("keytype", "number")]),
        ),
    ]
