# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schluessel', '0005_auto_20170423_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='keylogentry',
            name='key_comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kommentar'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='key_deposit',
            field=models.FloatField(blank=True, null=True, verbose_name='Kaution'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='key_keytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schluessel.KeyType', verbose_name='Schlüssel-Typ'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='key_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nummer'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='person_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Straße + Hausnummer'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='person_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='person_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='person_firstname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='person_mobile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mobil'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='person_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nachname'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='person_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='keylogentry',
            name='person_plz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='keylogentry',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schluessel.Key', verbose_name='Schlüssel'),
        ),
        migrations.AlterField(
            model_name='keylogentry',
            name='operation',
            field=models.CharField(choices=[('G', 'Ausgabe'), ('R', 'Rückgabe'), ('C', 'Erstellung'), ('E', 'Bearbeitung')], max_length=1, verbose_name='Vorgang'),
        ),
    ]
