# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schluessel', '0007_savedkeychange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedkeychange',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Datum'),
        ),
    ]
