# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schluessel", "0008_auto_20170530_1723"),
    ]

    operations = [
        migrations.AddField(
            model_name="key",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
    ]
