# Generated by Django 3.2.3 on 2021-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schluessel", "0013_auto_20170608_2233"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keylogentry",
            name="key_active",
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name="Aktiv"),
        ),
    ]
