# Generated by Django 3.2.3 on 2021-05-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aufgaben", "0004_aufgabe_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aufgabe",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="aufgben-attachments", verbose_name="Anhang"),
        ),
    ]
