# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 14:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnzahlPosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.IntegerField(default=1, verbose_name='Anzahl')),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knr', models.IntegerField(unique=True, verbose_name='Kundennummer')),
                ('organisation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organisation')),
                ('suborganisation', models.TextField(blank=True, max_length=500, null=True, verbose_name='SubOrganisation')),
                ('anrede', models.CharField(blank=True, choices=[('w', 'Frau'), ('m', 'Herr')], max_length=5, null=True, verbose_name='Anrede')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nachname')),
                ('vorname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vorname')),
                ('strasse', models.CharField(max_length=100, verbose_name='Straße')),
                ('plz', models.CharField(max_length=20, verbose_name='PLZ')),
                ('stadt', models.CharField(max_length=200, verbose_name='Stadt')),
                ('kommentar', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Kommentar')),
            ],
        ),
        migrations.CreateModel(
            name='Posten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('einzelpreis', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Einzelpreis')),
                ('mwst', models.IntegerField(default=19, verbose_name='Mehrwertsteuersatz')),
            ],
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zweck der Rechnung')),
                ('rnr', models.IntegerField(unique=True, verbose_name='Rechnungsnummer')),
                ('rdatum', models.DateField(default=datetime.date.today, verbose_name='Rechnungsdatum')),
                ('ldatum', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Lieferdatum')),
                ('gestellt', models.BooleanField(verbose_name='Rechnung gestellt?')),
                ('einleitung', models.TextField(max_length=1000, verbose_name='Einleitender Text nach "Sehr geehrte..."')),
                ('ersteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechnung.Kategorie')),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechnung.Kunde')),
                ('posten', models.ManyToManyField(through='rechnung.AnzahlPosten', to='rechnung.Posten')),
            ],
        ),
        migrations.AddField(
            model_name='anzahlposten',
            name='posten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechnung.Posten'),
        ),
        migrations.AddField(
            model_name='anzahlposten',
            name='rechnung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechnung.Rechnung'),
        ),
        migrations.AlterUniqueTogether(
            name='anzahlposten',
            unique_together=set([('posten', 'rechnung')]),
        ),
    ]
