# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import rechnung.models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posten',
            name='mwst',
            field=models.IntegerField(choices=[(0, '0 %'), (7, '7 %'), (19, '19 %')], default=7, verbose_name='Mehrwertsteuersatz'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='fdatum',
            field=models.DateField(default=rechnung.models.get_faelligkeit_default, verbose_name='Fälligkeitsdatum'),
        ),
    ]
