# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 21:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import rechnung.models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnung', '0002_auto_20160613_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kategorie *'),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='knr',
            field=models.IntegerField(unique=True, verbose_name='Kundennummer *'),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='plz',
            field=models.CharField(max_length=20, verbose_name='PLZ *'),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='stadt',
            field=models.CharField(max_length=200, verbose_name='Stadt *'),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='strasse',
            field=models.CharField(max_length=100, verbose_name='Straße *'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='einleitung',
            field=models.TextField(max_length=1000, verbose_name='Einleitender Text nach "Sehr geehrte..." *'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='fdatum',
            field=models.DateField(default=rechnung.models.get_faelligkeit_default, verbose_name='Fälligkeitsdatum *'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='rdatum',
            field=models.DateField(default=datetime.date.today, verbose_name='Rechnungsdatum *'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='rnr',
            field=models.IntegerField(unique=True, verbose_name='Rechnungsnummer *'),
        ),
    ]
