# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnung', '0002_auto_20160604_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posten',
            name='mwst',
            field=models.DecimalField(choices=[(0.0, '0 %'), (0.07, '7 %'), (0.19, '19 %')], decimal_places=4, default=0.19, max_digits=7, verbose_name='Mehrwertsteuersatz'),
        ),
    ]
