# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rechnung", "0003_auto_20160622_1341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posten",
            name="einzelpreis",
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name="Einzelpreis"),
        ),
        migrations.AlterField(
            model_name="posten",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Bezeichnung"),
        ),
    ]
