# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnung', '0003_auto_20160604_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posten',
            name='mwst',
            field=models.IntegerField(choices=[(0, '0 %'), (7, '7 %'), (19, '19 %')], default=19, verbose_name='Mehrwertsteuersatz'),
        ),
    ]
