# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import rechnung.models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnung', '0004_auto_20160604_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='fdatum',
            field=models.DateField(default=rechnung.models.get_faelligkeit_default, verbose_name='Fälligkeitsdatum'),
        ),
    ]
