# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnung', '0005_rechnung_fdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='bezahlt',
            field=models.BooleanField(default=False, verbose_name='Rechnung beglichen?'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='gestellt',
            field=models.BooleanField(default=False, verbose_name='Rechnung gestellt?'),
        ),
    ]
