# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rechnung", "0005_kunde_land"),
    ]

    operations = [
        migrations.AddField(
            model_name="kunde",
            name="titel",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Titel"),
        ),
    ]
