# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rechnung", "0008_mahnung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mahnung",
            name="wievielte",
            field=models.IntegerField(null=True, verbose_name="Wievielte Mahnung?"),
        ),
    ]
