# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-07 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnung', '0010_auto_20161001_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahnung',
            name='einleitung',
            field=models.TextField(default='', max_length=3000, verbose_name='Einleitender Text nach "Sehr geehrte..." *'),
        ),
    ]
