# Generated by Django 3.2.3 on 2021-06-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rechnung", "0011_auto_20161008_2334"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rechnung",
            options={"verbose_name_plural": "Rechnungen"},
        ),
    ]
