# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-07 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnung', '0011_mahnung_einleitung'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahnung',
            name='gerichtlich',
            field=models.BooleanField(default=False, verbose_name='Gerichtliche Schritte androhen?'),
        ),
    ]
