# Generated by Django 4.0.3 on 2022-04-16 22:07
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def regenerate_epc_qr_codes(apps, schema_editor):
    Rechnung = apps.get_model("rechnung", "Rechnung")
    for rechnung in Rechnung.objects.all():
        if Decimal(0.1) < rechnung.gesamtsumme < Decimal(999999999.99):
            rechnung.regen_epc_qr_code()


class Migration(migrations.Migration):
    dependencies = [
        ("rechnung", "0012_alter_rechnung_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rechnung",
            name="epc_qr_code",
            field=models.ImageField(blank=True, upload_to="epc_qr_code"),
        ),
        migrations.RunPython(regenerate_epc_qr_codes),
        migrations.AlterField(
            model_name="posten",
            name="anzahl",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Anzahl",
            ),
        ),
        migrations.AlterField(
            model_name="posten",
            name="einzelpreis",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Einzelpreis ohne MWSt in EUR",
                max_digits=15,
                verbose_name="Einzelpreis",
            ),
        ),
    ]
