name: dependabot for pre-commit

on:
    schedule:
        # * is a special character in YAML so you have to quote this string
        - cron: '0 19 * * 5' # At 19:00 on Friday.
    workflow_dispatch:

jobs:
    update_pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-python@v3
              with:
                  python-version: '3.10'
                  cache: 'pip'
                  cache-dependency-path: 'requirements_dev.txt'
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pre-commit
            - name: install update pre-commit
              run: |
                  pre-commit autoupdate
                  pre-commit autoupdate --config .pre-commit-only-line-endings-config.yaml
            - name: Commit pre-commit file if changed
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'Automated Change: updated pre-commit requirements'
